services:
  waha:
    image: devlikeapro/waha:latest
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./waha-data:/app/data
    environment:
      - API_PORT=3000
      - WORKERS_FOLDER=/app/data/workers
    dns:
      - 1.1.1.1
      - 8.8.8.8