version: '3.9'

services:
  waha:
    image: devlikeapro/waha:latest
    ports:
      - "3000:8080"  # Porta 3000 pública → 8080 interna
    environment:
      - PORT=8080
      - WAHA_TOKEN=changeme
      - NODE_ENV=production
